<form action="https://ibill.my/merchant/?ng=client/iview/opencart/" method="POST">
	<input type="hidden" value="<?php echo $apiid; ?>" name="apiid"> <!-- Your API ID -->
    <input type="hidden" value="<?php echo $apisecret?>" name="apisecret"> <!-- Your Secret Key -->
    <input type="hidden" value="<?php echo $apiname?>" name="apiname"> <!-- Your customer name -->
    <input type="hidden" value="<?php echo $apiemail?>" name="apiemail"> <!-- Your customer email -->
    <input type="hidden" value="<?php echo $apiphone?>" name="apiphone"> <!-- Your customer phone -->
    <input type="hidden" value="<?php echo $apiaddress?>" name="apiaddress"> <!-- Your customer address -->
    <input type="hidden" value="<?php echo $apiamount?>" name="apiamount"> <!-- Total amount customer need to pay -->
    <input type="hidden" value="<?php echo $apidetail?>" name="apidetail"> <!-- Detail invoice/payment -->
    <input type="hidden" value="<?php echo $apiorderid?>" name="apiorderid"> <!-- Order ID generated by your system -->
    <div class="buttons">
        <div class="pull-right">
            <input type="submit" value="<?php echo $button_confirm; ?>" id="button-submit" class="btn btn-primary" />
        </div>
    </div>
</form>